version : "3.7"

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    volumes:
    - wordpress:/var/www/wordpress
    depends_on:
    - wordpress
    env_file: .env
    ports:
    - "443:443"
    restart: on-failure
    networks:
    - inception

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: unless-stopped
    ports:
    - "3306:3306"
    env_file: .env
    volumes:
    - mariadb:/var/lib/mysql
    networks:
    - inception
  
  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    env_file: .env
    depends_on:
    - mariadb
    volumes:
    - wordpress:/var/www/wordpress
    ports:
    - "9000:9000"
    networks:
    - inception

networks:
  inception:

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: /home/test1/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: /home/test1/data/mariadb
